# Generated by Django 4.0.1 on 2022-01-27 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0004_rename_watchlist_review_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='descripton',
            new_name='description',
        ),
    ]
